version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 10
  build:
    commands:
      - nodejs --version
artifacts:
  files:
    - index.html
    - resume.pdf
    - favicon.ico
    - styles/*
    - images/*